services:
  api:
    build: .
    ports:
      - "2342:2342"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - sgbr_network

  postgres:
    image: postgres:15-alpine
    container_name: sgbr_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sgbr_network

  mongodb:
    image: mongo:6.0
    container_name: sgbr_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sgbr_network

  redis:
    image: redis:7-alpine
    container_name: sgbr_redis
    ports:
      - "6379:6379"
    networks:
      - sgbr_network

networks:
  sgbr_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: